name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential meson cmake lua5.4 xorg-dev libgl1-mesa-dev libxkbcommon-dev
      - name: Build
        run: |
          meson setup build
          meson compile -C build
