name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make libgl1-mesa-dev libglfw3-dev libglew-dev libsqlite3-dev zlib1g-dev
      - name: Build
        run: |
          cd src
          make -j$(nproc)
