name: snapshot
on: [push]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make libgl1-mesa-dev libglfw3-dev libglew-dev libsqlite3-dev zlib1g-dev curl zip
      - name: Build
        run: |
          ./snapshot.sh
      - name: Upload snapshot
        env:
          SECRET: ${{ secrets.ELIDRAGON_UPLOAD_TOKEN }}
        run: |
          ./upload.sh



