name: snapshot
on: [push]
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake lua5.3 curl zip
      - name: Build ubuntu snapshot
        run: |
          ./snapshot.sh
      - name: Build windows snapshot
        run: |
          ./snapshot.sh mingw
      - name: Upload snapshots
        env:
          SECRET: ${{ secrets.ELIDRAGON_UPLOAD_TOKEN }}
        run: |
          ./upload.sh



